### ISSUE TITLE
Question about sub-groups

### ISSUE THREAD

**Issue by matanox** [d3/d3-chord#24]
Hi,

I guess that [the following feature](https://stackoverflow.com/questions/43278964/how-to-add-categories-to-your-chord-diagram-in-d3-js) (object hierarchy on the circumference) is not directly supported, but just to make sure, can anyone please explain what are "subgroups" as per the readme of this module? I'm not entirely sure about the `groups` and `subgroups` terminology in the docs for chord diagrams. 

Thanks in advance!

**Comment by Fil** [comment]
Please open a [discussion](https://github.com/d3/d3/discussions) instead of an issue.
