### ISSUE TITLE
Ribbon positioning in canvas

### ISSUE THREAD

**Issue by rodighiero** [d3/d3-chord#5]
We are building a force-direct diagram with chords diagrams at each node. We experienced a bug, chords are fixed at the origin of the canvas without any possibility of positioning.

**Comment by mbostock** [comment]
This is not a bug; this is the documented behavior. As the README says, you must use context.translate or similar to change the origin of the ribbon.

**Comment by rodighiero** [comment]
Finally I translated (x,y) and translated back (-x,-y) for each ribbon, and it works fine.
You were right, thanks for helping.

**Comment by mbostock** [comment]
I would recommend using _context_.save and _context_.restore, but either would work.
